development:
  adapter: postgresql
  encoding: unicode
  database: hackmit_development
  pool: 5
  username: hackmit
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: hackmit_test
  pool: 5
  username: hackmit
  password: password1
